### PR TITLE
Add more femboys

### PR DESCRIPTION
**Pull request by ya-sach1**
Added more femboys since the users were complaining about the lack of the aforementioned.

### CODE REVIEW

**Comment by dapper-gh** [comment]
Hi! Thanks for your PR. However, there are a few issues that need fixing.
1. This doesn't respond well to some viewports. Try using your browser's developer tools to resize your window to phone size (I used 360x640).
2. This relies on external hosting sites. Instead of using `catbox.moe` (or any other external hosting site), include the image in the `web-src` folder.
3. A random selection from a set of images would be a nice-to-have.

**Comment by ya-sach1** [comment]
I will fix asap and add the random selection 👍🏻

**Comment by dapper-gh** [comment]
This is much better! However, there are still some issues.
1. The "g" in "Image" is cut off. (and maybe the "p" in "Dapper"?) I'm on a 1920x1080 screen, but it's a problem on a variety of viewports.
2. Some of the images feel blurry.
3. To me, it feels like there's not enough padding, although I can see the appeal of a "packed" design.
4. Your HTML needs some cleaning up - there's an element with an empty `class` attribute, plenty of classes don't do anything, and one-element classes should be replaced with `id`.
5. `import` statements should be at the top of a file.
6. Your formatter automatically changed some of the existing code.

**Comment by ya-sach1** [comment]
I will try my best to fix it; I resized the images before adding them as I felt that they were too heavy but I'll just get the full res ones

**Comment by dapper-gh** [comment]
Some of the problems have been fixed, but on further reflection, I'd rather not have the homepage for my website be filled with gay hentai of dubious legality.

**Pull request closed without merging**
