### PR TITLE
dapper > dabber

### PR DESCRIPTION
**Pull request by ya-sach1**
I changed all the remaining `dabber`'s to `dapper`

### CODE REVIEW

**Review by dapper-gh — CHANGES_REQUESTED** [review]
You messed up the capitalization in some places. Also, you broke some links.

**Review by dapper-gh — CHANGES_REQUESTED** [review]
Better, but some capitalization is still wrong (ShareX config creator and meta keywords). Also, what's with the indentation?

**Comment by ya-sach1** [comment]
Fixed that, my formatter did thing itself lmao.

**Review by dapper-gh — APPROVED** [review]
Well done.

**Pull request merged**
